# Generated by Django 2.2.7 on 2019-11-19 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dt_nasc', models.DateField()),
                ('cep', models.CharField(help_text='Digite o CEp do seu endereço', max_length=8)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=50)),
                ('foto', models.ImageField(default='profile_pics/no-image-icon.png', upload_to='profile_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_de_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome tipo de objeto', max_length=200)),
                ('descricao', models.TextField(help_text='Insirta uma breve descrição do objeto', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do objeto', max_length=200)),
                ('autor', models.CharField(help_text='Digite o nome do autor, cantor, banda, criador, marca etc...', max_length=200)),
                ('descricao', models.TextField(help_text='Insirta uma breve descrição do objeto', max_length=1000)),
                ('foto', models.ImageField(default='item_pics/no-image-icon.png', upload_to='item_pics/')),
                ('status', models.CharField(choices=[('e', 'Emprestado'), ('i', 'Indisponível'), ('d', 'Disponível')], default='d', help_text='Status do item', max_length=1)),
                ('dtCadastro', models.DateTimeField(auto_now_add=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrows.Profile')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrows.Tipo_de_Item')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtEmprestimo', models.DateField()),
                ('dtDevolucao', models.DateField()),
                ('aberto', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrows.Item')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrows.Profile')),
            ],
            options={
                'ordering': ['dtDevolucao'],
            },
        ),
    ]
