# Generated by Django 2.2.7 on 2019-11-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_de_Item',
            new_name='TipoItem',
        ),
    ]
