# Generated by Django 2.2.7 on 2019-11-20 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0002_auto_20191119_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['dtCadastro']},
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='dtCadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='cep',
            field=models.CharField(help_text='Digite o CEP do seu endereço', max_length=8),
        ),
    ]
