# Generated by Django 2.2.7 on 2019-11-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0003_auto_20191120_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='foto',
            field=models.ImageField(default='media/no-image-icon.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='media/no-image-icon.png', upload_to='media/'),
        ),
    ]
