# Generated by Django 2.2.7 on 2019-11-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0004_auto_20191122_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='foto',
            field=models.ImageField(default='media/item_pics/no-image-item.png', upload_to='media/item_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='media/profile_pics/no-image-icon.png', upload_to='media/profile_pics/'),
        ),
    ]
