# Generated by Django 2.2.7 on 2019-11-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0006_auto_20191125_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='foto',
            field=models.ImageField(default='media/item_pics/no-image-item.png', upload_to='media/item_pics/'),
        ),
    ]
