# Generated by Django 2.2.7 on 2019-11-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0007_auto_20191125_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='foto',
            field=models.ImageField(default='item_pics/no-image-item.png', upload_to='item_pics'),
        ),
    ]
