# Generated by Django 2.2.7 on 2019-11-26 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0008_auto_20191125_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
