# Generated by Django 2.2.7 on 2019-11-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0009_auto_20191126_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dt_nasc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
