# Generated by Django 2.2.7 on 2019-11-27 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0010_auto_20191126_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='profile_pics/no-image-icon.png', upload_to='profile_pics'),
        ),
    ]
