# Generated by Django 2.2.7 on 2019-11-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0012_auto_20191127_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='aberto',
            field=models.BooleanField(null=True),
        ),
    ]
