# Generated by Django 2.2.7 on 2019-11-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0013_auto_20191127_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-aberto', '-dtEmprestimo']},
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dtCadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dtDevolucao',
            field=models.DateField(null=True, verbose_name='Data da Devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dtEmprestimo',
            field=models.DateField(verbose_name='Data do Empréstimo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(help_text='Insirta uma breve descrição do objeto', max_length=1000, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dtCadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.ForeignKey(help_text='Selecione o tipo de objeto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrows.TipoItem'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dt_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='tipoitem',
            name='descricao',
            field=models.TextField(help_text='Insira uma breve descrição do tipo de objeto', max_length=1000, verbose_name='Descrição'),
        ),
    ]
